### ISSUE TITLE
any idea why my job fails on travis?

### ISSUE THREAD

**Issue by ptrwllrt** [finom/github-embedder#1]
https://travis-ci.org/barcamperfurt/barcamperfurt/builds/162584678
It should do the following:
- pull https://github.com/barcamperfurt/barcamperfurt
- build
- push to https://github.com/barcamperfurt/barcamperfurt.github.io

The clone however , sadly the script doesn't provide good output on the reasons.

**Comment by finom** [comment]
>  sadly the script doesn't provide good output on the reasons.

The reason is an error can contain repository name which can use private info like GH_TOKEN. That's why it doesn't output any useful information :(

It seems you [did not provide your username](https://github.com/barcamperfurt/barcamperfurt/blob/master/package.json#L27) at repository name [like there](https://github.com/finom/github-embed/blob/master/package.json#L20).

If you still getting issues please reopen this issue at [deploy-to-git](https://github.com/finom/deploy-to-git), this repo is about code embed.

**Comment by finom** [comment]
Nice to see that your issue is fixed.

**Comment by ptrwllrt** [comment]
;-) I was about to comment here. Thanks for checking again! And sorry for the faulty repo, I'm not sure how it ended up here...
